# Generated by Django 5.2.7 on 2025-12-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskCompleteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_box', models.BooleanField(default=False)),
            ],
        ),
    ]
