# Generated by Django 5.2.7 on 2025-12-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0002_usertaskcompletemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTaskCompleteModel',
        ),
        migrations.AddField(
            model_name='sitemodels',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
