# Generated by Django 5.2.7 on 2025-12-14 02:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0003_delete_usertaskcompletemodel_sitemodels_is_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteModels',
            new_name='Task',
        ),
    ]
