# Generated by Django 5.2.7 on 2025-12-15 15:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0004_rename_sitemodels_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='SiteModels',
        ),
    ]
